Extend 'describe' with support for more messages
effuse/profuse pull request #56
Opened 2016-07-05 16:24 UTC by yallop

Extend 'describe' with support for more messages and tidy up error, string and file handling in the `fusedump` code.

2016-07-06 23:00 UTC, dsheets commented on lib/profuse_7_23.ml
> +             (UInt32.to_int32 size)
`Getxattr` and `Setxattr` are missing the name strings.

2016-07-06 23:04 UTC, dsheets commented on lib/profuse_7_23.ml
> +           Printf.sprintf "name=%s %s" name n
`Link` prints the name twice (`name` was already parsed and put in the constructor) and does not print the oldnodeid from the structure.

2016-07-06 23:07 UTC, dsheets commented on lib/profuse_7_23.ml
> +         | Bmap _r -> ""
I would rather `Flush`, `Fsyncdir`, `Fsync`, and `Bmap` say FIXME or TODO or something so the user knows that the serialization is not complete.

2016-07-06 23:08 UTC, dsheets commented
I haven't tested the refactoring parts but if it works then I'm very happy with it. Thanks for cleaning that stuff up!

2016-09-29 15:50 UTC, yallop commented on lib/profuse_7_23.ml
> +           Printf.sprintf "name=%s %s" name n
Fixed (a00028e).

2016-09-29 15:50 UTC, yallop commented on lib/profuse_7_23.ml
> +         | Bmap _r -> ""
Fixed (0c766e6).

2016-11-15 13:48 UTC, dsheets requested changes
Just a few more changes -- sorry!

2016-11-15 13:48 UTC, dsheets commented on lib/profuse_7_23.ml
> +        (Struct.File_lock.describe lk)
I think this is missing `lk_flags`?

2016-11-15 13:48 UTC, dsheets commented on lib/profuse_7_23.ml
> +           Printf.sprintf "name=%s size=%ld flags%ld="
s/flags%ld=/flags=%ld/

2016-11-15 13:48 UTC, dsheets commented on lib/profuse_7_8.ml
> +           Printf.sprintf "size=%ld flags%ld="
s/flags%ld=/flags=%ld/

2016-11-15 13:48 UTC, dsheets commented on lib/profuse_7_8.ml
> +         | Getxattr r ->
`Getxattr` and `Setxattr` are missing the name extraction like in 7.23.

2016-11-15 13:48 UTC, dsheets commented on lib/profuse_7_8.ml
> +           Printf.sprintf "name=%s %s" name n
This is double printing the name and not printing the old node id.

2016-11-15 13:48 UTC, dsheets commented on lib/profuse_7_8.ml
> +         | Bmap _r -> ""
This should print `FIXME` rather than empty string.

2016-11-18 16:30 UTC, yallop commented
> Just a few more changes -- sorry!

I've addressed these in 78d8ba8.

2016-11-18 16:39 UTC, dsheets approved these changes

2016-11-18 16:39 UTC, dsheets commented
LGTM. Thanks!

2016-11-18 16:39 UTC, merged