Refactor Dirent.of_list
effuse/profuse pull request #58
Opened 2016-07-15 11:00 UTC by yallop

2016-07-15 12:46 UTC, dsheets commented
This may fix <https://forums.docker.com/t/files-missing-inside-host-mounted-volume/16721>. Could you write a test case that reproduces the behavio(u)r and demonstrates the fix?

2016-07-15 12:58 UTC, dsheets commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) name
Is there a fix for this in a newer ctypes?

2016-07-15 13:03 UTC, yallop commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) name
No, but there's [this](https://github.com/yallop/ocaml-memcpy).

2016-07-15 13:08 UTC, dsheets commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) name
Ok, it is a fine with me to make that a dependency.

2016-09-29 16:00 UTC, yallop commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) name
See 9598ae6.

2016-11-15 14:14 UTC, dsheets requested changes
Partitioning will really help with complexity. Also, it looks like there is at least one missing `memcpy`.

2016-11-15 14:14 UTC, dsheets commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) name
It looks like you replaced one `String.iter` copy but not this one. Could you please replace all of the `String.iter` copies?

2016-11-15 14:14 UTC, dsheets commented on lib/profuse_7_23.ml
> +      let listing, count = filter_listing listing offset read_size in
It would be great if this would partition the listing into the set for this packet and the remaining set and return the remaining set along with the constructed packet. This will help callers to reduce re-traversal for multi-packet listings.

2016-11-29 15:02 UTC, yallop commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) name
I've replaced the remaining `String.iter` calls now (d1e1545).

2016-11-29 15:05 UTC, yallop commented on lib/profuse_7_23.ml
> +      let listing, count = filter_listing listing offset read_size in
Would you mind if I added partitioning in a separate PR?

2016-11-29 15:07 UTC, dsheets commented on lib/profuse_7_23.ml
> +      let listing, count = filter_listing listing offset read_size in
A separate PR is fine. Thanks!

2016-11-29 15:10 UTC, dsheets approved these changes

2016-11-29 15:10 UTC, merged