Add DELETE and INVAL_INODE notifications
effuse/profuse pull request #71
Opened 2017-02-17 11:34 UTC by dsheets

The `NOTIFY_DELETE` commit has been carried on the `fuse-7.23` branch for a long time but the `NOTIFY_INVAL_INODE` commit is new and required for attribute and page cache invalidation.

2017-02-23 15:40 UTC, yallop requested changes

2017-02-23 15:40 UTC, yallop commented on lib/profuse_7_23.ml
> +        String.iter (fun c -> !sp <-@ c; sp := !sp +@ 1) filename;
Perhaps worth doing the better copy now -- see [`Inval_entry.store`](https://github.com/dsheets/profuse/blob/9b4a38df6433598a2d9935d6cf41708061b38401/lib/profuse_7_23.ml#L1037-L1039) for an example.

2017-02-28 18:41 UTC, dsheets commented
Ok, I replace the horrible `String.iter` copy with a use of `Memcpy`. I also fixed a stray tab. Please have a look.

2017-03-01 07:31 UTC, yallop approved these changes

2017-03-01 10:54 UTC, merged